/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiIPD;

import dbc.DataBaseConnection;
import iris.pupil_detection.IRISPUPIL_Detection;
import iris.pupil_detection.RescaleImage;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import programManagment.ProgramManagment;
import programManagment.UserManagment;

/**
 *
 * @author Aleksa
 */
public class MainGUI extends javax.swing.JFrame {

      private IRISPUPIL_Detection ipd;
      private DataManagmentGUI dmg;
    
    public MainGUI(ProgramManagment pm) {
        initComponents();
        this.pm = pm;
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
    }
    
  

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        selectedPic = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cannyIrisImage = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        htIrisImage = new javax.swing.JLabel();
        cannyPupilImage = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        htPupilImage = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        eyeDetectedImage = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        editedImage = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        userData = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iris-Pupil detection");
        setBackground(new java.awt.Color(153, 153, 153));
        setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        setMinimumSize(new java.awt.Dimension(860, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectButton.setText("select image");
        selectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectButtonMouseClicked(evt);
            }
        });
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });
        getContentPane().add(selectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 105, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("selected image");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 118, -1));

        selectedPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/empty.png"))); // NOI18N
        selectedPic.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(selectedPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 256, 160));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("canny iris");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 101, -1));

        cannyIrisImage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(cannyIrisImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 256, 160));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("hough transformed iris");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        htIrisImage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(htIrisImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 256, 160));

        cannyPupilImage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(cannyPupilImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 256, 160));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 153));
        jLabel9.setText("Iris-Pupil detected");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 150, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setText("canny pupil");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, 20));
        jLabel10.getAccessibleContext().setAccessibleDescription("");

        htPupilImage.setBackground(new java.awt.Color(204, 204, 204));
        htPupilImage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(htPupilImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 256, 160));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 153));
        jLabel12.setText("hough transformed pupil");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 210, -1));

        eyeDetectedImage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(eyeDetectedImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 256, 160));

        jButton1.setText("Insert in database");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, -1, -1));

        jButton2.setText("Compare with database images");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, -1, -1));

        editedImage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(editedImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 256, 160));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 153));
        jLabel15.setText("Radius:  \n");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 760, 50));

        userData.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(userData, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 950, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hi-tech-tehnologii-glaz.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1024, 680));
        jLabel1.setMinimumSize(new java.awt.Dimension(1024, 680));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 1450, 840));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectButtonMouseClicked
      
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        BufferedImage choosedImage = null;
        BufferedImage choosedImage2 = null;
        BufferedImage choosedImage3 = null;
        BufferedImage choosedImage4 = null;
        BufferedImage choosedImage5 = null;
          try {
              choosedImage = ImageIO.read(f);
              choosedImage2 = ImageIO.read(f);
              choosedImage3 = ImageIO.read(f);
              choosedImage4 = ImageIO.read(f);
              choosedImage5 = ImageIO.read(f);
          } catch (IOException ex) {
              JOptionPane.showMessageDialog(null, ex);
          }
        ipd = new IRISPUPIL_Detection(RescaleImage.scale(choosedImage), RescaleImage.scale(choosedImage2), 
                RescaleImage.scale(choosedImage3), RescaleImage.scale(choosedImage4), RescaleImage.scale(choosedImage5));
        
        BufferedImage selectedImage = ipd.getProjectImage();
        selectedPic.setIcon(new ImageIcon(selectedImage));
        
        BufferedImage cannyPupil = ipd.getPupil();
        cannyPupilImage.setIcon(new ImageIcon(cannyPupil));
        
        BufferedImage htPupil = ipd.getHtPupil();
        htPupilImage.setIcon(new ImageIcon(htPupil));
        
        BufferedImage cannyIris = ipd.getIris();
        cannyIrisImage.setIcon(new ImageIcon(cannyIris));
        
        BufferedImage htIris = ipd.getHtIris();
        htIrisImage.setIcon(new ImageIcon(htIris));
        
        BufferedImage wholeImage = ipd.getWholeImage();
        editedImage.setIcon(new ImageIcon(wholeImage));
        
        BufferedImage eyeDetected = ipd.getEyeDetected();
       
        eyeDetectedImage.setIcon(new ImageIcon(eyeDetected));
        
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);

          try {
              ImageIO.write(ipd.getEyeDetected(), "jpg", new File("image.jpg"));
          } catch (IOException ex) {
              Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
          }
        
        jLabel15.setText("Ovo je radius sarenice: " + ipd.getIrisRadius() + "\n ovo je radius zjenice: " + ipd.getPupilRadius());
    }//GEN-LAST:event_selectButtonMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        dmg = new DataManagmentGUI(this.pm);
        dmg.setVisible(true);
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
     
        pm.compareUsers(new File("image.jpg"), userData);
    }//GEN-LAST:event_jButton2MouseClicked

    
    // Logical variabless
    private ProgramManagment pm;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cannyIrisImage;
    private javax.swing.JLabel cannyPupilImage;
    private javax.swing.JLabel editedImage;
    private javax.swing.JLabel eyeDetectedImage;
    private javax.swing.JLabel htIrisImage;
    private javax.swing.JLabel htPupilImage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton selectButton;
    private javax.swing.JLabel selectedPic;
    private javax.swing.JLabel userData;
    // End of variables declaration//GEN-END:variables
}
